# ======== Users section 
### post user 
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "Prem",
    "email":"hjkhkjkjgjhjhghjgf@h.com",
    "phone":"12134433",
    "password":"123"
      
}

###delete
DELETE http://localhost:8000/api/v1/transactions 
#header
Content-Type: application/json

#body
 ["6639e7752b3c589026c43f72"]

